services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5430:5432'
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8070:8080"